#########################################################
# Request Test OData - Bootcamp Globant | SAP - CAP
# Logistic And Shipping                 | Final Project
# Lucas Gancia                          | Author
#########################################################

@base_url = http://localhost:4004

### -----------------------------------------------------
GET {{base_url}}/logistic/

### -----------------------------------------------------
GET {{base_url}}/logistic/$metadata


### -----------------------------------------------------
### --> PACKAGES
###     CREATE - POST
### -----------------------------------------------------
POST {{base_url}}/logistic/Packages
Content-Type: application/json

{
    "weight": 234.11,
    "dimensions_length": 1223.20,
    "dimensions_height": 903.87,
    "dimensions_width": 341.45,
    "receiver_name": "Pedro Enrique Garcia",
    "receiver_cel": "09876542",
    "receiver_email": "pedro_enrique@ejemplo.com",
    "destination_city": "City Example 5",
    "destination_street": "Street Example 5",
    "destination_address": "Street Example 5, 2134",
    "destination_neighborhood": "Neighborhood Example 5",
    "taken": false
}


### -----------------------------------------------------
### --> PACKAGES
###     READ - GET
###     - GET {{base_url}}/logistic/Packages?$expand=vehicle
###     - GET {{base_url}}/logistic/Vehicles?$expand=packages
### -----------------------------------------------------
# @name getPackageID
GET {{base_url}}/logistic/Packages


### -----------------------------------------------------
### --> PACKAGES
###     UPDATE - PATCH
### -----------------------------------------------------
@packageID = {{getPackageID.response.body.$.value[0].ID}} 

PATCH {{base_url}}/logistic/Packages({{packageID}})
Content-Type: application/json

{
    "weight": 63.24,
    "taken": false
}


### -----------------------------------------------------
### --> PACKAGES
###     DELETE - DELETE by ID
### -----------------------------------------------------
DELETE {{base_url}}/logistic/Packages({{packageID}})

### -----------------------------------------------------
### --> PACKAGES
###     CUSTOM ACTION
###         - Package Delivered
### -----------------------------------------------------
POST {{base_url}}/logistic/Packages/actions/delivered
Content-Type: application/json

{
    "idPack": "{{packageID}}"
}